#copy script files to RPiZ
---
- name: Copy python scripts to home dir
  hosts: raspberry_pi_zero
  become: yes
  gather_facts: no
  tasks: 
    - name: Copy gpio_button_sample.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/gpio_button_sample.py
        dest: /home/jonmitten/gpio_button_sample.py
        mode: '0755'
    - name: Copy test_gpio.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/test_gpio.py 
        dest: /home/jonmitten/test_gpio.py
        mode: '0755'
    - name: Copy led_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/led_test.py
        dest: /home/jonmitten/led_test.py
        mode: '0755'
    - name: Copy mqtt_button_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/mqtt_button_test.py
        dest: /home/jonmitten/mqtt_button_test.py
        mode: '0755'
    - name: Run `python3 led_test.py` from home dir
      command: python3 /home/jonmitten/led_test.py
      args:
        chdir: /home/jonmitten/