---
- name: Deploy button press script to Raspberry Pi devices
  hosts: flowers
  become: yes
  gather_facts: yes
  tasks: 
    - name: Copy gpio_button_sample.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/gpio_button_sample.py
        dest: /home/jonmitten/gpio_button_sample.py
        mode: '0755'
      tags:
        - button
        - gpio

    - name: Copy test_gpio.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/test_gpio.py 
        dest: /home/jonmitten/test_gpio.py
        mode: '0755'
      tags:
        - gpio
        - test

    - name: Copy led_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/led_test.py
        dest: /home/jonmitten/led_test.py
        mode: '0755'
      tags:
        - led
        - gpio
        - test

    - name: Copy mqtt_button_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/mqtt_button_test.py
        dest: /home/jonmitten/mqtt_button_test.py
        mode: '0755'
      tags:
        - mqtt
        - button
        - test

    - name: Copy mqtt_pub_sub_button_test.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/mqtt_pub_sub_button_test.py
        dest: /home/jonmitten/mqtt_pub_sub_button_test.py
        mode: '0755'
      tags:
        - mqtt
        - button
        - test
        - pub
        - sub

    - name: Copy pir_test.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/pir_test.py
        dest: /home/jonmitten/pir_test.py
        mode: '0755'
      tags:
        - pir
        - test

    - name: Run `python3 led_test.py` from home dir
      command: python3 /home/jonmitten/led_test.py
      args:
        chdir: /home/jonmitten/
      tags:
        - test
        - led
        - blink

    - name: Run `python pir_test.py` from home dir
      command: python3 /home/jonmitten/pir_test.py
      args:
        chdir: /home/jonmitten/
      tags:
        - test
        - led
        - blink
        - pir

