---
- name: Deploy button press script to Raspberry Pi devices
  hosts: flowers
  become: yes
  gather_facts: yes
  tasks: 
    - name: Copy gpio_button_sample.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/gpio_button_sample.py
        dest: /home/jonmitten/gpio_button_sample.py
        mode: '0755'
      tags:
        - button
        - GPIO

    - name: Copy GPIO.test.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/GPIO.test.py
        dest: /home/jonmitten/GPIO.test.py
        mode: '0755'
      tags:
        - GPIO
        - test

    - name: Copy led_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/blink.test.py
        dest: /home/jonmitten/blink.test.py
        mode: '0755'
      tags:
        - led
        - GPIO
        - test

    - name: Copy mqtt_button_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/button.mqtt.test.py
        dest: /home/jonmitten/button.mqtt.test.py
        mode: '0755'
      tags:
        - mqtt
        - button
        - test

    - name: Copy pub_sub_button.test.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/pub_sub_button.test.py
        dest: /home/jonmitten/pub_sub_button.test.py
        mode: '0755'
      tags:
        - mqtt
        - button
        - test
        - pub
        - sub

    - name: Copy pir.test.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/pir.test.py
        dest: /home/jonmitten/pir.test.py
        mode: '0755'
      tags:
        - pir
        - test

    - name: Run `python3 blink.test.py` GPIO python test complete
      command: python3 /home/jonmitten/blink.test.py
      args:
        chdir: /home/jonmitten/
      tags:
        - test
        - led
        - blink

    - name: Run `python pir.test.py` from home dir
      command: python3 /home/jonmitten/pir.test.py
      args:
        chdir: /home/jonmitten/
      tags:
        - test
        - led
        - blink
        - pir

