#copy script files to RPiZ
---
- name: Copy python scripts to home dir
  hosts: flowers
  become: yes
  gather_facts: no
  tasks:
    - name: Copy mqtt_button_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/blink.py
        dest: /home/jonmitten/blink.py
        mode: '0755'
    - name: Copy blink to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/blink.test.py
        dest: /home/jonmitten/blink.test.py
        mode: '0755'
    - name: Run `python3 blink.py` copy_script complete
      command: python3 /home/jonmitten/blink.py
      args:
        chdir: /home/jonmitten/