---
- name: Install Mosquitto on RPi
  hosts: raspberry_pi_zero
  become: yes
  gather_facts: yes
  gather_subset:
    - '!all'
    - 'min'  
  tasks:
    - name: Ensure the system is updated
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Mosquitto MQTT Broker
      apt:
        name: mosquitto
        state: present

    - name: Install Mosquitto clients
      apt:
        name: mosquitto-clients
        state: present

    - name: Create Mosquitto configuration directory
      file:
        path: /etc/mosquitto/conf.d
        state: directory
        mode: '0755'

    - name: Configure Mosquitto
      copy:
        dest: /etc/mosquitto/conf.d/singing.conf
        content: |
          listener 1883
          allow_anonymous true
          log_type all
          log_dest file /var/log/mosquitto/mosquitto.log

    - name: Restart Mosquitto service
      systemd:
        name: mosquitto
        state: restarted
        enabled: yes

        