---
- name: Deploy button press script to Raspberry Pi devices
  hosts: flowers
  become: yes
  gather_facts: yes
  tasks:
    - name: Copy led_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/led_test.py
        dest: /home/jonmitten/led_test.py
        mode: '0755'
      tags:
        - led
        - gpio
        - test

    - name: Copy pir_test.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/pir_test.py
        dest: /home/jonmitten/pir_test.py
        mode: '0755'
      tags:
        - pir
        - test

    - name: Run `python3 led_test.py` from home dir
      command: python3 /home/jonmitten/led_test.py
      args:
        chdir: /home/jonmitten/
      tags:
        - test
        - led
        - blink


