---
- name: Deploy button press script to Raspberry Pi devices
  hosts: flowers
  become: yes
  gather_facts: yes
  tasks:
    - name: Copy led_test to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/blink.test.py
        dest: /home/jonmitten/blink.test.py
        mode: '0755'
      tags:
        - led
        - GPIO
        - test

    - name: Copy pir.test.py to home dir
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/pir.test.py
        dest: /home/jonmitten/pir.test.py
        mode: '0755'
      tags:
        - pir
        - test

    - name: Run `python3 blink.test.py` pir_test complete
      command: python3 /home/jonmitten/blink.test.py
      args:
        chdir: /home/jonmitten/
      tags:
        - test
        - led
        - blink


