---
- name: Install python3 GPIO
  hosts: raspberry_pi_zero
  become: yes
  tasks: 
    - name: Update and upgrade apt packages
      apt: 
        update_cache: yes
        upgrade: dist

    - name: Install Python GPIO Library
      apt: 
        name: python3-rpi.gpio
        state: present
