---
- name: Universal Setup Init
  hosts: raspberry_pi_zero
  become: yes
  gather_facts: no
  tasks: 
    - name: Testing task 
      debug:
        msg: "Testing..."
    - name: Update and upgrade apt packages
      apt: 
        update_cache: yes
        upgrade: dist
