---
- name: Deploy button press script to Raspberry Pi devices
  hosts: raspberry_pi_zero
  become: yes
  gather_facts: yes
  gather_subset:
    - '!all'
    - 'min'  
  tasks: 
    - name: Copy the button press script to the RPi Zeros
      copy:
        src: /Users/jonmitten/development/singing_loud_flowers/scripts/test.gpio_button.py 
        dest: /home/jonmitten/test.gpio_button.py
        mode: '0755'